### ISSUE TITLE
Named commit and rollback to any named stage 

### ISSUE THREAD

**Issue by XiLaiTL** [antfu/magic-string-stack#1]
### Clear and concise description of the problem

The function `commit` update the `MagicString` to the new one.
 I wonder If it is possible that you can commit with name, and rollback the named stage to use the relative position of any committed one? 
 

### Suggested solution

Like this:
```ts
const s = new MagicStringStack('problems = 99') //now we named it `origin`

s.replace('problems', 'issues')
  .append('var ')

s.toString() 
s.original 

s.commit("Middle") // now we named the staged `Middle`

s.original
s.replace('issues', 'problems')
s.toString() 

//many named stage

s.rollback('Middle') //now we go back to 'Middle' stage

s.rollback('origin')  //now we go back the origin one
//...

s.generateMap()


```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
While it's not hard to do, I wonder what's the use case of this? Using string names could make things complicated as we also need to handle the naming collisions. I feel that a linear `.commit` and `.rollback` might be enough already

**Comment by XiLaiTL** [comment]
We can maintain a string array as the stack while maintaining the MagicString stack.

Use `nameStack= ["name"].concat(nameStack)` to push the name.
Use `nameStack.splice(0, 1)` to pop the name.
Use `nameStack.length - 1 - nameStack.indexOf("name")` to get the index of target stage.

With maintaining the name stack, it handles the naming collisions by rollbacking to the newest named stage.
